/**
 * Hand-written TypeScript stubs for the CORS Policy Management RPCs added to
 * resource.proto. These mirror the pattern generated by protoc-gen-grpc-web
 * and are needed because globular-web-client@1.2.17 predates the new methods.
 *
 * Wire field layout (proto3):
 *   GetServicesCorsPoliciesRqst  – empty
 *   ServiceCorsPolicy            – id(1,str) name(2,str) allow_all_origins(3,bool) allowed_origins(4,str)
 *   GetServicesCorsPoliciesRsp   – policies(1, repeated ServiceCorsPolicy)
 *   SetServiceCorsPolicyRqst     – id(1,str) allow_all_origins(2,bool) allowed_origins(3,str)
 *   SetServiceCorsPolicyRsp      – empty
 */

// google-protobuf is a transitive dep of globular-web-client — types via @types/google-protobuf
import * as jspb from 'google-protobuf'
import * as grpcWeb from 'grpc-web'

// ── GetServicesCorsPoliciesRqst ───────────────────────────────────────────────

export class GetServicesCorsPoliciesRqst extends jspb.Message {
  serializeBinary(): Uint8Array {
    const writer = new jspb.BinaryWriter()
    GetServicesCorsPoliciesRqst.serializeBinaryToWriter(this, writer)
    return writer.getResultBuffer()
  }

  static serializeBinaryToWriter(_msg: GetServicesCorsPoliciesRqst, _writer: jspb.BinaryWriter): void {
    // no fields
  }

  static deserializeBinary(_bytes: Uint8Array): GetServicesCorsPoliciesRqst {
    return new GetServicesCorsPoliciesRqst()
  }

  static deserializeBinaryFromReader(
    msg: GetServicesCorsPoliciesRqst,
    reader: jspb.BinaryReader
  ): GetServicesCorsPoliciesRqst {
    while (reader.nextField()) {
      if (reader.isEndGroup()) break
      reader.skipField()
    }
    return msg
  }

  toObject(_includeInstance?: boolean): GetServicesCorsPoliciesRqst.AsObject {
    return {}
  }

  static toObject(
    _includeInstance: boolean,
    _msg: GetServicesCorsPoliciesRqst
  ): GetServicesCorsPoliciesRqst.AsObject {
    return {}
  }
}

export namespace GetServicesCorsPoliciesRqst {
  export type AsObject = Record<string, never>
}

// ── ServiceCorsPolicy ─────────────────────────────────────────────────────────

export class ServiceCorsPolicy extends jspb.Message {
  private id_: string = ''
  private name_: string = ''
  private allowAllOrigins_: boolean = false
  private allowedOrigins_: string = ''

  getId(): string { return this.id_ }
  setId(value: string): this { this.id_ = value; return this }

  getName(): string { return this.name_ }
  setName(value: string): this { this.name_ = value; return this }

  getAllowAllOrigins(): boolean { return this.allowAllOrigins_ }
  setAllowAllOrigins(value: boolean): this { this.allowAllOrigins_ = value; return this }

  getAllowedOrigins(): string { return this.allowedOrigins_ }
  setAllowedOrigins(value: string): this { this.allowedOrigins_ = value; return this }

  serializeBinary(): Uint8Array {
    const writer = new jspb.BinaryWriter()
    ServiceCorsPolicy.serializeBinaryToWriter(this, writer)
    return writer.getResultBuffer()
  }

  static serializeBinaryToWriter(msg: ServiceCorsPolicy, writer: jspb.BinaryWriter): void {
    if (msg.getId().length > 0) writer.writeString(1, msg.getId())
    if (msg.getName().length > 0) writer.writeString(2, msg.getName())
    if (msg.getAllowAllOrigins()) writer.writeBool(3, msg.getAllowAllOrigins())
    if (msg.getAllowedOrigins().length > 0) writer.writeString(4, msg.getAllowedOrigins())
  }

  static deserializeBinary(bytes: Uint8Array): ServiceCorsPolicy {
    const reader = new jspb.BinaryReader(bytes)
    const msg = new ServiceCorsPolicy()
    return ServiceCorsPolicy.deserializeBinaryFromReader(msg, reader)
  }

  static deserializeBinaryFromReader(
    msg: ServiceCorsPolicy,
    reader: jspb.BinaryReader
  ): ServiceCorsPolicy {
    while (reader.nextField()) {
      if (reader.isEndGroup()) break
      const field = reader.getFieldNumber()
      switch (field) {
        case 1: msg.setId(reader.readString()); break
        case 2: msg.setName(reader.readString()); break
        case 3: msg.setAllowAllOrigins(reader.readBool()); break
        case 4: msg.setAllowedOrigins(reader.readString()); break
        default: reader.skipField(); break
      }
    }
    return msg
  }

  toObject(_includeInstance?: boolean): ServiceCorsPolicy.AsObject {
    return ServiceCorsPolicy.toObject(false, this)
  }

  static toObject(_includeInstance: boolean, msg: ServiceCorsPolicy): ServiceCorsPolicy.AsObject {
    return {
      id: msg.getId(),
      name: msg.getName(),
      allowAllOrigins: msg.getAllowAllOrigins(),
      allowedOrigins: msg.getAllowedOrigins(),
    }
  }
}

export namespace ServiceCorsPolicy {
  export type AsObject = {
    id: string
    name: string
    allowAllOrigins: boolean
    allowedOrigins: string
  }
}

// ── GetServicesCorsPoliciesRsp ────────────────────────────────────────────────

export class GetServicesCorsPoliciesRsp extends jspb.Message {
  private policies_: ServiceCorsPolicy[] = []

  getPoliciesList(): ServiceCorsPolicy[] { return this.policies_ }
  setPoliciesList(value: ServiceCorsPolicy[]): this { this.policies_ = value; return this }
  addPolicies(value: ServiceCorsPolicy): this { this.policies_.push(value); return this }
  clearPoliciesList(): this { this.policies_ = []; return this }

  serializeBinary(): Uint8Array {
    const writer = new jspb.BinaryWriter()
    GetServicesCorsPoliciesRsp.serializeBinaryToWriter(this, writer)
    return writer.getResultBuffer()
  }

  static serializeBinaryToWriter(msg: GetServicesCorsPoliciesRsp, writer: jspb.BinaryWriter): void {
    const policies = msg.getPoliciesList()
    if (policies.length > 0) {
      writer.writeRepeatedMessage(1, policies, ServiceCorsPolicy.serializeBinaryToWriter)
    }
  }

  static deserializeBinary(bytes: Uint8Array): GetServicesCorsPoliciesRsp {
    const reader = new jspb.BinaryReader(bytes)
    const msg = new GetServicesCorsPoliciesRsp()
    return GetServicesCorsPoliciesRsp.deserializeBinaryFromReader(msg, reader)
  }

  static deserializeBinaryFromReader(
    msg: GetServicesCorsPoliciesRsp,
    reader: jspb.BinaryReader
  ): GetServicesCorsPoliciesRsp {
    while (reader.nextField()) {
      if (reader.isEndGroup()) break
      const field = reader.getFieldNumber()
      switch (field) {
        case 1: {
          const value = new ServiceCorsPolicy()
          reader.readMessage(value, ServiceCorsPolicy.deserializeBinaryFromReader)
          msg.addPolicies(value)
          break
        }
        default: reader.skipField(); break
      }
    }
    return msg
  }

  toObject(_includeInstance?: boolean): GetServicesCorsPoliciesRsp.AsObject {
    return GetServicesCorsPoliciesRsp.toObject(false, this)
  }

  static toObject(
    _includeInstance: boolean,
    msg: GetServicesCorsPoliciesRsp
  ): GetServicesCorsPoliciesRsp.AsObject {
    return {
      policiesList: msg.getPoliciesList().map(p => ServiceCorsPolicy.toObject(false, p)),
    }
  }
}

export namespace GetServicesCorsPoliciesRsp {
  export type AsObject = {
    policiesList: ServiceCorsPolicy.AsObject[]
  }
}

// ── SetServiceCorsPolicyRqst ──────────────────────────────────────────────────

export class SetServiceCorsPolicyRqst extends jspb.Message {
  private id_: string = ''
  private allowAllOrigins_: boolean = false
  private allowedOrigins_: string = ''

  getId(): string { return this.id_ }
  setId(value: string): this { this.id_ = value; return this }

  getAllowAllOrigins(): boolean { return this.allowAllOrigins_ }
  setAllowAllOrigins(value: boolean): this { this.allowAllOrigins_ = value; return this }

  getAllowedOrigins(): string { return this.allowedOrigins_ }
  setAllowedOrigins(value: string): this { this.allowedOrigins_ = value; return this }

  serializeBinary(): Uint8Array {
    const writer = new jspb.BinaryWriter()
    SetServiceCorsPolicyRqst.serializeBinaryToWriter(this, writer)
    return writer.getResultBuffer()
  }

  static serializeBinaryToWriter(msg: SetServiceCorsPolicyRqst, writer: jspb.BinaryWriter): void {
    if (msg.getId().length > 0) writer.writeString(1, msg.getId())
    if (msg.getAllowAllOrigins()) writer.writeBool(2, msg.getAllowAllOrigins())
    if (msg.getAllowedOrigins().length > 0) writer.writeString(3, msg.getAllowedOrigins())
  }

  static deserializeBinary(bytes: Uint8Array): SetServiceCorsPolicyRqst {
    const reader = new jspb.BinaryReader(bytes)
    const msg = new SetServiceCorsPolicyRqst()
    return SetServiceCorsPolicyRqst.deserializeBinaryFromReader(msg, reader)
  }

  static deserializeBinaryFromReader(
    msg: SetServiceCorsPolicyRqst,
    reader: jspb.BinaryReader
  ): SetServiceCorsPolicyRqst {
    while (reader.nextField()) {
      if (reader.isEndGroup()) break
      const field = reader.getFieldNumber()
      switch (field) {
        case 1: msg.setId(reader.readString()); break
        case 2: msg.setAllowAllOrigins(reader.readBool()); break
        case 3: msg.setAllowedOrigins(reader.readString()); break
        default: reader.skipField(); break
      }
    }
    return msg
  }

  toObject(_includeInstance?: boolean): SetServiceCorsPolicyRqst.AsObject {
    return SetServiceCorsPolicyRqst.toObject(false, this)
  }

  static toObject(
    _includeInstance: boolean,
    msg: SetServiceCorsPolicyRqst
  ): SetServiceCorsPolicyRqst.AsObject {
    return {
      id: msg.getId(),
      allowAllOrigins: msg.getAllowAllOrigins(),
      allowedOrigins: msg.getAllowedOrigins(),
    }
  }
}

export namespace SetServiceCorsPolicyRqst {
  export type AsObject = {
    id: string
    allowAllOrigins: boolean
    allowedOrigins: string
  }
}

// ── SetServiceCorsPolicyRsp ───────────────────────────────────────────────────

export class SetServiceCorsPolicyRsp extends jspb.Message {
  serializeBinary(): Uint8Array {
    const writer = new jspb.BinaryWriter()
    SetServiceCorsPolicyRsp.serializeBinaryToWriter(this, writer)
    return writer.getResultBuffer()
  }

  static serializeBinaryToWriter(
    _msg: SetServiceCorsPolicyRsp,
    _writer: jspb.BinaryWriter
  ): void {
    // no fields
  }

  static deserializeBinary(_bytes: Uint8Array): SetServiceCorsPolicyRsp {
    return new SetServiceCorsPolicyRsp()
  }

  static deserializeBinaryFromReader(
    msg: SetServiceCorsPolicyRsp,
    reader: jspb.BinaryReader
  ): SetServiceCorsPolicyRsp {
    while (reader.nextField()) {
      if (reader.isEndGroup()) break
      reader.skipField()
    }
    return msg
  }

  toObject(_includeInstance?: boolean): SetServiceCorsPolicyRsp.AsObject {
    return {}
  }

  static toObject(
    _includeInstance: boolean,
    _msg: SetServiceCorsPolicyRsp
  ): SetServiceCorsPolicyRsp.AsObject {
    return {}
  }
}

export namespace SetServiceCorsPolicyRsp {
  export type AsObject = Record<string, never>
}

// ── gRPC-web Client ───────────────────────────────────────────────────────────

export class ResourceServiceCorsClient {
  private client_: grpcWeb.GrpcWebClientBase
  private hostname_: string

  constructor(
    hostname: string,
    _credentials?: null | { [index: string]: string },
    options?: null | { [index: string]: unknown }
  ) {
    const opts: grpcWeb.GrpcWebClientBaseOptions = { ...(options ?? {}), format: 'text' }
    this.client_ = new grpcWeb.GrpcWebClientBase(opts)
    this.hostname_ = hostname.replace(/\/+$/, '')
  }

  getServicesCorsPolicies(
    request: GetServicesCorsPoliciesRqst,
    metadata: grpcWeb.Metadata | undefined,
    callback: (err: grpcWeb.RpcError, response: GetServicesCorsPoliciesRsp) => void
  ): grpcWeb.ClientReadableStream<GetServicesCorsPoliciesRsp> {
    return this.client_.rpcCall(
      `${this.hostname_}/resource.ResourceService/GetServicesCorsPolicies`,
      request,
      metadata ?? {},
      new grpcWeb.MethodDescriptor(
        '/resource.ResourceService/GetServicesCorsPolicies',
        grpcWeb.MethodType.UNARY,
        GetServicesCorsPoliciesRqst,
        GetServicesCorsPoliciesRsp,
        (r: GetServicesCorsPoliciesRqst) => r.serializeBinary(),
        GetServicesCorsPoliciesRsp.deserializeBinary
      ),
      callback
    )
  }

  setServiceCorsPolicy(
    request: SetServiceCorsPolicyRqst,
    metadata: grpcWeb.Metadata | undefined,
    callback: (err: grpcWeb.RpcError, response: SetServiceCorsPolicyRsp) => void
  ): grpcWeb.ClientReadableStream<SetServiceCorsPolicyRsp> {
    return this.client_.rpcCall(
      `${this.hostname_}/resource.ResourceService/SetServiceCorsPolicy`,
      request,
      metadata ?? {},
      new grpcWeb.MethodDescriptor(
        '/resource.ResourceService/SetServiceCorsPolicy',
        grpcWeb.MethodType.UNARY,
        SetServiceCorsPolicyRqst,
        SetServiceCorsPolicyRsp,
        (r: SetServiceCorsPolicyRqst) => r.serializeBinary(),
        SetServiceCorsPolicyRsp.deserializeBinary
      ),
      callback
    )
  }
}
